// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import type { Model } from "../types.ts";

export const AGNES_MODELS = {
	"sapiens-ai/agnes-1.5-lite": {
		id: "sapiens-ai/agnes-1.5-lite",
		name: "Agnes 1.5 Lite",
		api: "openai-completions",
		provider: "agnes",
		baseUrl: "https://agnes-ai.com/api/v1",
		compat: {"supportsStore":false,"supportsDeveloperRole":false,"supportsReasoningEffort":true,"maxTokensField":"max_tokens","supportsStrictMode":false,"supportsLongCacheRetention":false},
		reasoning: false,
		input: ["text", "image"],
		cost: {
			input: 1.2e-7,
			output: 6e-7,
			cacheRead: 0,
			cacheWrite: 0,
		},
		contextWindow: 256000,
		maxTokens: 32768,
	} satisfies Model<"openai-completions">,
	"sapiens-ai/agnes-1.5-pro": {
		id: "sapiens-ai/agnes-1.5-pro",
		name: "Agnes 1.5 Pro",
		api: "openai-completions",
		provider: "agnes",
		baseUrl: "https://agnes-ai.com/api/v1",
		compat: {"supportsStore":false,"supportsDeveloperRole":false,"supportsReasoningEffort":true,"maxTokensField":"max_tokens","supportsStrictMode":false,"supportsLongCacheRetention":false},
		reasoning: true,
		input: ["text"],
		cost: {
			input: 1.6e-7,
			output: 8e-7,
			cacheRead: 0,
			cacheWrite: 0,
		},
		contextWindow: 256000,
		maxTokens: 32768,
	} satisfies Model<"openai-completions">,
} as const;
